# Generated by Django 3.0.2 on 2020-02-04 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('weekday', models.BooleanField()),
                ('days', models.BigIntegerField()),
                ('instructor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Classlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('slot', models.IntegerField()),
                ('date', models.DateField()),
                ('cartype', models.BooleanField()),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Classname')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
