# Generated by Django 3.0.2 on 2020-02-06 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('cartype', models.BooleanField()),
                ('classlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Classlist')),
            ],
        ),
    ]
