# Generated by Django 3.0.2 on 2020-02-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_bookdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=20)),
                ('offervalue', models.IntegerField()),
                ('offertype', models.CharField(max_length=20)),
            ],
        ),
    ]
